module lock_validation_wrapper (
    input  logic       clk,
    input  logic       resetN,
    input  logic       srst,
    input  logic       enter_al,
    input  logic [3:0] switches,
    output logic       error,
    output logic       correct
);

    logic        done;
    logic        enter_d;
    logic        storage_rst;
    logic [3:0]  code;

    // codeStorage has no resetN port — its counter uses synchronous sclr only.
    // storage_rst bridges the gap: it goes high on either srst or hard reset (!resetN).
    // Because sclr is sampled at clk posedge, resetN must be held low for at least
    // one full clk cycle for the counter to actually clear.
    // lock_validation resets immediately (async negedge resetN), so a brief mismatch
    // window exists, but enter_d = 0 during reset prevents any ctr advancement.
    assign storage_rst = srst || !resetN;

    // clk is expected to be clk1ms (1 kHz) — generated by clock1 in the top level
    codeStorage u_codeStorage (
        .clk              (clk),
        .wren             (1'b0),
        .ctrRst           (storage_rst),
        .clk_en           (enter_d),
        .rStartingAddress (5'd0),
        .wStartingAddress (5'd0),
        .dataIn           (4'd0),
        .done             (done),
        .dataOut          (code)
    );

    lock_validation u_lock_validation (
        .clk        (clk),
        .done       (done),
        .resetN     (resetN),
        .srst       (srst),
        .enter_al   (enter_al),
        .code       (code),
        .switches   (switches),
        .error      (error),
        .correct    (correct),
        .enter_d    (enter_d),
        .state_regt ()
    );

endmodule
