// megafunction wizard: %LPM_COUNTER%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: LPM_COUNTER 

// ============================================================
// File Name: TwentyBitsCounter.v
// Megafunction Name(s):
// 			LPM_COUNTER
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 25.1std.0 Build 1129 10/21/2025 SC Lite Edition
// ************************************************************


//Copyright (C) 2025  Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and any partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus Prime License Agreement,
//the Altera IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Altera and sold by Altera or its authorized distributors.  Please
//refer to the Altera Software License Subscription Agreements 
//on the Quartus Prime software download page.


//lpm_counter DEVICE_FAMILY="Cyclone V" lpm_direction="UP" lpm_port_updown="PORT_UNUSED" lpm_width=28 clock q sclr
//VERSION_BEGIN 25.1 cbx_cycloneii 2025:10:22:10:31:27:SC cbx_lpm_add_sub 2025:10:22:10:31:27:SC cbx_lpm_compare 2025:10:22:10:31:27:SC cbx_lpm_counter 2025:10:22:10:31:27:SC cbx_lpm_decode 2025:10:22:10:31:27:SC cbx_mgl 2025:10:22:10:31:44:SC cbx_nadder 2025:10:22:10:31:27:SC cbx_stratix 2025:10:22:10:31:27:SC cbx_stratixii 2025:10:22:10:31:26:SC  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = lut 28 reg 28 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  TwentyBitsCounter_cntr
	( 
	clock,
	q,
	sclr) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	output   [27:0]  q;
	input   sclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   sclr;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire	[27:0]	wire_counter_reg_bit_d;
	wire	[27:0]	wire_counter_reg_bit_asdata;
	reg	[27:0]	counter_reg_bit;
	wire	[27:0]	wire_counter_reg_bit_ena;
	wire	[27:0]	wire_counter_reg_bit_sload;
	wire  [0:0]   wire_counter_comb_bita_0cout;
	wire  [0:0]   wire_counter_comb_bita_1cout;
	wire  [0:0]   wire_counter_comb_bita_2cout;
	wire  [0:0]   wire_counter_comb_bita_3cout;
	wire  [0:0]   wire_counter_comb_bita_4cout;
	wire  [0:0]   wire_counter_comb_bita_5cout;
	wire  [0:0]   wire_counter_comb_bita_6cout;
	wire  [0:0]   wire_counter_comb_bita_7cout;
	wire  [0:0]   wire_counter_comb_bita_8cout;
	wire  [0:0]   wire_counter_comb_bita_9cout;
	wire  [0:0]   wire_counter_comb_bita_10cout;
	wire  [0:0]   wire_counter_comb_bita_11cout;
	wire  [0:0]   wire_counter_comb_bita_12cout;
	wire  [0:0]   wire_counter_comb_bita_13cout;
	wire  [0:0]   wire_counter_comb_bita_14cout;
	wire  [0:0]   wire_counter_comb_bita_15cout;
	wire  [0:0]   wire_counter_comb_bita_16cout;
	wire  [0:0]   wire_counter_comb_bita_17cout;
	wire  [0:0]   wire_counter_comb_bita_18cout;
	wire  [0:0]   wire_counter_comb_bita_19cout;
	wire  [0:0]   wire_counter_comb_bita_20cout;
	wire  [0:0]   wire_counter_comb_bita_21cout;
	wire  [0:0]   wire_counter_comb_bita_22cout;
	wire  [0:0]   wire_counter_comb_bita_23cout;
	wire  [0:0]   wire_counter_comb_bita_24cout;
	wire  [0:0]   wire_counter_comb_bita_25cout;
	wire  [0:0]   wire_counter_comb_bita_26cout;
	wire  [0:0]   wire_counter_comb_bita_0sumout;
	wire  [0:0]   wire_counter_comb_bita_1sumout;
	wire  [0:0]   wire_counter_comb_bita_2sumout;
	wire  [0:0]   wire_counter_comb_bita_3sumout;
	wire  [0:0]   wire_counter_comb_bita_4sumout;
	wire  [0:0]   wire_counter_comb_bita_5sumout;
	wire  [0:0]   wire_counter_comb_bita_6sumout;
	wire  [0:0]   wire_counter_comb_bita_7sumout;
	wire  [0:0]   wire_counter_comb_bita_8sumout;
	wire  [0:0]   wire_counter_comb_bita_9sumout;
	wire  [0:0]   wire_counter_comb_bita_10sumout;
	wire  [0:0]   wire_counter_comb_bita_11sumout;
	wire  [0:0]   wire_counter_comb_bita_12sumout;
	wire  [0:0]   wire_counter_comb_bita_13sumout;
	wire  [0:0]   wire_counter_comb_bita_14sumout;
	wire  [0:0]   wire_counter_comb_bita_15sumout;
	wire  [0:0]   wire_counter_comb_bita_16sumout;
	wire  [0:0]   wire_counter_comb_bita_17sumout;
	wire  [0:0]   wire_counter_comb_bita_18sumout;
	wire  [0:0]   wire_counter_comb_bita_19sumout;
	wire  [0:0]   wire_counter_comb_bita_20sumout;
	wire  [0:0]   wire_counter_comb_bita_21sumout;
	wire  [0:0]   wire_counter_comb_bita_22sumout;
	wire  [0:0]   wire_counter_comb_bita_23sumout;
	wire  [0:0]   wire_counter_comb_bita_24sumout;
	wire  [0:0]   wire_counter_comb_bita_25sumout;
	wire  [0:0]   wire_counter_comb_bita_26sumout;
	wire  [0:0]   wire_counter_comb_bita_27sumout;
	wire  aclr_actual;
	wire clk_en;
	wire cnt_en;
	wire [27:0]  data;
	wire  external_cin;
	wire  lsb_cin;
	wire  [27:0]  s_val;
	wire  [27:0]  safe_q;
	wire sload;
	wire sset;
	wire  updown_dir;
	wire  updown_lsb;
	wire  updown_other_bits;

	// synopsys translate_off
	initial
		counter_reg_bit[0:0] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[0:0] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[0:0] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[0:0] <= 1'b0;
			else if (wire_counter_reg_bit_sload[0:0] == 1'b1) counter_reg_bit[0:0] <= wire_counter_reg_bit_asdata[0:0];
			else  counter_reg_bit[0:0] <= wire_counter_reg_bit_d[0:0];
	// synopsys translate_off
	initial
		counter_reg_bit[1:1] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[1:1] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[1:1] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[1:1] <= 1'b0;
			else if (wire_counter_reg_bit_sload[1:1] == 1'b1) counter_reg_bit[1:1] <= wire_counter_reg_bit_asdata[1:1];
			else  counter_reg_bit[1:1] <= wire_counter_reg_bit_d[1:1];
	// synopsys translate_off
	initial
		counter_reg_bit[2:2] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[2:2] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[2:2] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[2:2] <= 1'b0;
			else if (wire_counter_reg_bit_sload[2:2] == 1'b1) counter_reg_bit[2:2] <= wire_counter_reg_bit_asdata[2:2];
			else  counter_reg_bit[2:2] <= wire_counter_reg_bit_d[2:2];
	// synopsys translate_off
	initial
		counter_reg_bit[3:3] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[3:3] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[3:3] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[3:3] <= 1'b0;
			else if (wire_counter_reg_bit_sload[3:3] == 1'b1) counter_reg_bit[3:3] <= wire_counter_reg_bit_asdata[3:3];
			else  counter_reg_bit[3:3] <= wire_counter_reg_bit_d[3:3];
	// synopsys translate_off
	initial
		counter_reg_bit[4:4] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[4:4] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[4:4] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[4:4] <= 1'b0;
			else if (wire_counter_reg_bit_sload[4:4] == 1'b1) counter_reg_bit[4:4] <= wire_counter_reg_bit_asdata[4:4];
			else  counter_reg_bit[4:4] <= wire_counter_reg_bit_d[4:4];
	// synopsys translate_off
	initial
		counter_reg_bit[5:5] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[5:5] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[5:5] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[5:5] <= 1'b0;
			else if (wire_counter_reg_bit_sload[5:5] == 1'b1) counter_reg_bit[5:5] <= wire_counter_reg_bit_asdata[5:5];
			else  counter_reg_bit[5:5] <= wire_counter_reg_bit_d[5:5];
	// synopsys translate_off
	initial
		counter_reg_bit[6:6] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[6:6] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[6:6] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[6:6] <= 1'b0;
			else if (wire_counter_reg_bit_sload[6:6] == 1'b1) counter_reg_bit[6:6] <= wire_counter_reg_bit_asdata[6:6];
			else  counter_reg_bit[6:6] <= wire_counter_reg_bit_d[6:6];
	// synopsys translate_off
	initial
		counter_reg_bit[7:7] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[7:7] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[7:7] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[7:7] <= 1'b0;
			else if (wire_counter_reg_bit_sload[7:7] == 1'b1) counter_reg_bit[7:7] <= wire_counter_reg_bit_asdata[7:7];
			else  counter_reg_bit[7:7] <= wire_counter_reg_bit_d[7:7];
	// synopsys translate_off
	initial
		counter_reg_bit[8:8] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[8:8] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[8:8] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[8:8] <= 1'b0;
			else if (wire_counter_reg_bit_sload[8:8] == 1'b1) counter_reg_bit[8:8] <= wire_counter_reg_bit_asdata[8:8];
			else  counter_reg_bit[8:8] <= wire_counter_reg_bit_d[8:8];
	// synopsys translate_off
	initial
		counter_reg_bit[9:9] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[9:9] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[9:9] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[9:9] <= 1'b0;
			else if (wire_counter_reg_bit_sload[9:9] == 1'b1) counter_reg_bit[9:9] <= wire_counter_reg_bit_asdata[9:9];
			else  counter_reg_bit[9:9] <= wire_counter_reg_bit_d[9:9];
	// synopsys translate_off
	initial
		counter_reg_bit[10:10] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[10:10] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[10:10] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[10:10] <= 1'b0;
			else if (wire_counter_reg_bit_sload[10:10] == 1'b1) counter_reg_bit[10:10] <= wire_counter_reg_bit_asdata[10:10];
			else  counter_reg_bit[10:10] <= wire_counter_reg_bit_d[10:10];
	// synopsys translate_off
	initial
		counter_reg_bit[11:11] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[11:11] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[11:11] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[11:11] <= 1'b0;
			else if (wire_counter_reg_bit_sload[11:11] == 1'b1) counter_reg_bit[11:11] <= wire_counter_reg_bit_asdata[11:11];
			else  counter_reg_bit[11:11] <= wire_counter_reg_bit_d[11:11];
	// synopsys translate_off
	initial
		counter_reg_bit[12:12] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[12:12] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[12:12] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[12:12] <= 1'b0;
			else if (wire_counter_reg_bit_sload[12:12] == 1'b1) counter_reg_bit[12:12] <= wire_counter_reg_bit_asdata[12:12];
			else  counter_reg_bit[12:12] <= wire_counter_reg_bit_d[12:12];
	// synopsys translate_off
	initial
		counter_reg_bit[13:13] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[13:13] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[13:13] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[13:13] <= 1'b0;
			else if (wire_counter_reg_bit_sload[13:13] == 1'b1) counter_reg_bit[13:13] <= wire_counter_reg_bit_asdata[13:13];
			else  counter_reg_bit[13:13] <= wire_counter_reg_bit_d[13:13];
	// synopsys translate_off
	initial
		counter_reg_bit[14:14] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[14:14] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[14:14] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[14:14] <= 1'b0;
			else if (wire_counter_reg_bit_sload[14:14] == 1'b1) counter_reg_bit[14:14] <= wire_counter_reg_bit_asdata[14:14];
			else  counter_reg_bit[14:14] <= wire_counter_reg_bit_d[14:14];
	// synopsys translate_off
	initial
		counter_reg_bit[15:15] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[15:15] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[15:15] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[15:15] <= 1'b0;
			else if (wire_counter_reg_bit_sload[15:15] == 1'b1) counter_reg_bit[15:15] <= wire_counter_reg_bit_asdata[15:15];
			else  counter_reg_bit[15:15] <= wire_counter_reg_bit_d[15:15];
	// synopsys translate_off
	initial
		counter_reg_bit[16:16] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[16:16] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[16:16] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[16:16] <= 1'b0;
			else if (wire_counter_reg_bit_sload[16:16] == 1'b1) counter_reg_bit[16:16] <= wire_counter_reg_bit_asdata[16:16];
			else  counter_reg_bit[16:16] <= wire_counter_reg_bit_d[16:16];
	// synopsys translate_off
	initial
		counter_reg_bit[17:17] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[17:17] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[17:17] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[17:17] <= 1'b0;
			else if (wire_counter_reg_bit_sload[17:17] == 1'b1) counter_reg_bit[17:17] <= wire_counter_reg_bit_asdata[17:17];
			else  counter_reg_bit[17:17] <= wire_counter_reg_bit_d[17:17];
	// synopsys translate_off
	initial
		counter_reg_bit[18:18] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[18:18] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[18:18] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[18:18] <= 1'b0;
			else if (wire_counter_reg_bit_sload[18:18] == 1'b1) counter_reg_bit[18:18] <= wire_counter_reg_bit_asdata[18:18];
			else  counter_reg_bit[18:18] <= wire_counter_reg_bit_d[18:18];
	// synopsys translate_off
	initial
		counter_reg_bit[19:19] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[19:19] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[19:19] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[19:19] <= 1'b0;
			else if (wire_counter_reg_bit_sload[19:19] == 1'b1) counter_reg_bit[19:19] <= wire_counter_reg_bit_asdata[19:19];
			else  counter_reg_bit[19:19] <= wire_counter_reg_bit_d[19:19];
	// synopsys translate_off
	initial
		counter_reg_bit[20:20] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[20:20] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[20:20] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[20:20] <= 1'b0;
			else if (wire_counter_reg_bit_sload[20:20] == 1'b1) counter_reg_bit[20:20] <= wire_counter_reg_bit_asdata[20:20];
			else  counter_reg_bit[20:20] <= wire_counter_reg_bit_d[20:20];
	// synopsys translate_off
	initial
		counter_reg_bit[21:21] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[21:21] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[21:21] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[21:21] <= 1'b0;
			else if (wire_counter_reg_bit_sload[21:21] == 1'b1) counter_reg_bit[21:21] <= wire_counter_reg_bit_asdata[21:21];
			else  counter_reg_bit[21:21] <= wire_counter_reg_bit_d[21:21];
	// synopsys translate_off
	initial
		counter_reg_bit[22:22] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[22:22] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[22:22] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[22:22] <= 1'b0;
			else if (wire_counter_reg_bit_sload[22:22] == 1'b1) counter_reg_bit[22:22] <= wire_counter_reg_bit_asdata[22:22];
			else  counter_reg_bit[22:22] <= wire_counter_reg_bit_d[22:22];
	// synopsys translate_off
	initial
		counter_reg_bit[23:23] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[23:23] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[23:23] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[23:23] <= 1'b0;
			else if (wire_counter_reg_bit_sload[23:23] == 1'b1) counter_reg_bit[23:23] <= wire_counter_reg_bit_asdata[23:23];
			else  counter_reg_bit[23:23] <= wire_counter_reg_bit_d[23:23];
	// synopsys translate_off
	initial
		counter_reg_bit[24:24] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[24:24] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[24:24] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[24:24] <= 1'b0;
			else if (wire_counter_reg_bit_sload[24:24] == 1'b1) counter_reg_bit[24:24] <= wire_counter_reg_bit_asdata[24:24];
			else  counter_reg_bit[24:24] <= wire_counter_reg_bit_d[24:24];
	// synopsys translate_off
	initial
		counter_reg_bit[25:25] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[25:25] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[25:25] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[25:25] <= 1'b0;
			else if (wire_counter_reg_bit_sload[25:25] == 1'b1) counter_reg_bit[25:25] <= wire_counter_reg_bit_asdata[25:25];
			else  counter_reg_bit[25:25] <= wire_counter_reg_bit_d[25:25];
	// synopsys translate_off
	initial
		counter_reg_bit[26:26] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[26:26] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[26:26] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[26:26] <= 1'b0;
			else if (wire_counter_reg_bit_sload[26:26] == 1'b1) counter_reg_bit[26:26] <= wire_counter_reg_bit_asdata[26:26];
			else  counter_reg_bit[26:26] <= wire_counter_reg_bit_d[26:26];
	// synopsys translate_off
	initial
		counter_reg_bit[27:27] = 0;
	// synopsys translate_on
	always @ ( posedge clock or  posedge aclr_actual)
		if (aclr_actual == 1'b1) counter_reg_bit[27:27] <= 1'b0;
		else if  (wire_counter_reg_bit_ena[27:27] == 1'b1) 
			if (sclr == 1'b1) counter_reg_bit[27:27] <= 1'b0;
			else if (wire_counter_reg_bit_sload[27:27] == 1'b1) counter_reg_bit[27:27] <= wire_counter_reg_bit_asdata[27:27];
			else  counter_reg_bit[27:27] <= wire_counter_reg_bit_d[27:27];
	assign
		wire_counter_reg_bit_asdata = (({28{sset}} & s_val) | ({28{(~ sset)}} & data)),
		wire_counter_reg_bit_d = {wire_counter_comb_bita_27sumout[0:0], wire_counter_comb_bita_26sumout[0:0], wire_counter_comb_bita_25sumout[0:0], wire_counter_comb_bita_24sumout[0:0], wire_counter_comb_bita_23sumout[0:0], wire_counter_comb_bita_22sumout[0:0], wire_counter_comb_bita_21sumout[0:0], wire_counter_comb_bita_20sumout[0:0], wire_counter_comb_bita_19sumout[0:0], wire_counter_comb_bita_18sumout[0:0], wire_counter_comb_bita_17sumout[0:0], wire_counter_comb_bita_16sumout[0:0], wire_counter_comb_bita_15sumout[0:0], wire_counter_comb_bita_14sumout[0:0], wire_counter_comb_bita_13sumout[0:0], wire_counter_comb_bita_12sumout[0:0], wire_counter_comb_bita_11sumout[0:0], wire_counter_comb_bita_10sumout[0:0], wire_counter_comb_bita_9sumout[0:0], wire_counter_comb_bita_8sumout[0:0], wire_counter_comb_bita_7sumout[0:0], wire_counter_comb_bita_6sumout[0:0], wire_counter_comb_bita_5sumout[0:0], wire_counter_comb_bita_4sumout[0:0], wire_counter_comb_bita_3sumout[0:0], wire_counter_comb_bita_2sumout[0:0], wire_counter_comb_bita_1sumout[0:0], wire_counter_comb_bita_0sumout[0:0]};
	assign
		wire_counter_reg_bit_ena = {28{(clk_en & (((cnt_en | sclr) | sset) | sload))}},
		wire_counter_reg_bit_sload = {28{(sset | sload)}};
	cyclonev_lcell_comb   counter_comb_bita_0
	( 
	.cin(lsb_cin),
	.combout(),
	.cout(wire_counter_comb_bita_0cout[0:0]),
	.datad(counter_reg_bit[0]),
	.dataf(updown_lsb),
	.shareout(),
	.sumout(wire_counter_comb_bita_0sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_0.extended_lut = "off",
		counter_comb_bita_0.lut_mask = 64'h000000000000FF00,
		counter_comb_bita_0.shared_arith = "off",
		counter_comb_bita_0.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_1
	( 
	.cin(wire_counter_comb_bita_0cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_1cout[0:0]),
	.datad(counter_reg_bit[1]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_1sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_1.extended_lut = "off",
		counter_comb_bita_1.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_1.shared_arith = "off",
		counter_comb_bita_1.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_2
	( 
	.cin(wire_counter_comb_bita_1cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_2cout[0:0]),
	.datad(counter_reg_bit[2]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_2sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_2.extended_lut = "off",
		counter_comb_bita_2.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_2.shared_arith = "off",
		counter_comb_bita_2.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_3
	( 
	.cin(wire_counter_comb_bita_2cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_3cout[0:0]),
	.datad(counter_reg_bit[3]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_3sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_3.extended_lut = "off",
		counter_comb_bita_3.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_3.shared_arith = "off",
		counter_comb_bita_3.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_4
	( 
	.cin(wire_counter_comb_bita_3cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_4cout[0:0]),
	.datad(counter_reg_bit[4]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_4sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_4.extended_lut = "off",
		counter_comb_bita_4.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_4.shared_arith = "off",
		counter_comb_bita_4.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_5
	( 
	.cin(wire_counter_comb_bita_4cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_5cout[0:0]),
	.datad(counter_reg_bit[5]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_5sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_5.extended_lut = "off",
		counter_comb_bita_5.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_5.shared_arith = "off",
		counter_comb_bita_5.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_6
	( 
	.cin(wire_counter_comb_bita_5cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_6cout[0:0]),
	.datad(counter_reg_bit[6]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_6sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_6.extended_lut = "off",
		counter_comb_bita_6.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_6.shared_arith = "off",
		counter_comb_bita_6.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_7
	( 
	.cin(wire_counter_comb_bita_6cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_7cout[0:0]),
	.datad(counter_reg_bit[7]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_7sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_7.extended_lut = "off",
		counter_comb_bita_7.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_7.shared_arith = "off",
		counter_comb_bita_7.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_8
	( 
	.cin(wire_counter_comb_bita_7cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_8cout[0:0]),
	.datad(counter_reg_bit[8]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_8sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_8.extended_lut = "off",
		counter_comb_bita_8.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_8.shared_arith = "off",
		counter_comb_bita_8.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_9
	( 
	.cin(wire_counter_comb_bita_8cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_9cout[0:0]),
	.datad(counter_reg_bit[9]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_9sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_9.extended_lut = "off",
		counter_comb_bita_9.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_9.shared_arith = "off",
		counter_comb_bita_9.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_10
	( 
	.cin(wire_counter_comb_bita_9cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_10cout[0:0]),
	.datad(counter_reg_bit[10]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_10sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_10.extended_lut = "off",
		counter_comb_bita_10.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_10.shared_arith = "off",
		counter_comb_bita_10.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_11
	( 
	.cin(wire_counter_comb_bita_10cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_11cout[0:0]),
	.datad(counter_reg_bit[11]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_11sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_11.extended_lut = "off",
		counter_comb_bita_11.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_11.shared_arith = "off",
		counter_comb_bita_11.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_12
	( 
	.cin(wire_counter_comb_bita_11cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_12cout[0:0]),
	.datad(counter_reg_bit[12]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_12sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_12.extended_lut = "off",
		counter_comb_bita_12.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_12.shared_arith = "off",
		counter_comb_bita_12.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_13
	( 
	.cin(wire_counter_comb_bita_12cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_13cout[0:0]),
	.datad(counter_reg_bit[13]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_13sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_13.extended_lut = "off",
		counter_comb_bita_13.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_13.shared_arith = "off",
		counter_comb_bita_13.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_14
	( 
	.cin(wire_counter_comb_bita_13cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_14cout[0:0]),
	.datad(counter_reg_bit[14]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_14sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_14.extended_lut = "off",
		counter_comb_bita_14.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_14.shared_arith = "off",
		counter_comb_bita_14.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_15
	( 
	.cin(wire_counter_comb_bita_14cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_15cout[0:0]),
	.datad(counter_reg_bit[15]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_15sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_15.extended_lut = "off",
		counter_comb_bita_15.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_15.shared_arith = "off",
		counter_comb_bita_15.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_16
	( 
	.cin(wire_counter_comb_bita_15cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_16cout[0:0]),
	.datad(counter_reg_bit[16]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_16sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_16.extended_lut = "off",
		counter_comb_bita_16.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_16.shared_arith = "off",
		counter_comb_bita_16.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_17
	( 
	.cin(wire_counter_comb_bita_16cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_17cout[0:0]),
	.datad(counter_reg_bit[17]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_17sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_17.extended_lut = "off",
		counter_comb_bita_17.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_17.shared_arith = "off",
		counter_comb_bita_17.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_18
	( 
	.cin(wire_counter_comb_bita_17cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_18cout[0:0]),
	.datad(counter_reg_bit[18]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_18sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_18.extended_lut = "off",
		counter_comb_bita_18.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_18.shared_arith = "off",
		counter_comb_bita_18.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_19
	( 
	.cin(wire_counter_comb_bita_18cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_19cout[0:0]),
	.datad(counter_reg_bit[19]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_19sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_19.extended_lut = "off",
		counter_comb_bita_19.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_19.shared_arith = "off",
		counter_comb_bita_19.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_20
	( 
	.cin(wire_counter_comb_bita_19cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_20cout[0:0]),
	.datad(counter_reg_bit[20]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_20sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_20.extended_lut = "off",
		counter_comb_bita_20.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_20.shared_arith = "off",
		counter_comb_bita_20.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_21
	( 
	.cin(wire_counter_comb_bita_20cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_21cout[0:0]),
	.datad(counter_reg_bit[21]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_21sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_21.extended_lut = "off",
		counter_comb_bita_21.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_21.shared_arith = "off",
		counter_comb_bita_21.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_22
	( 
	.cin(wire_counter_comb_bita_21cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_22cout[0:0]),
	.datad(counter_reg_bit[22]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_22sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_22.extended_lut = "off",
		counter_comb_bita_22.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_22.shared_arith = "off",
		counter_comb_bita_22.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_23
	( 
	.cin(wire_counter_comb_bita_22cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_23cout[0:0]),
	.datad(counter_reg_bit[23]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_23sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_23.extended_lut = "off",
		counter_comb_bita_23.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_23.shared_arith = "off",
		counter_comb_bita_23.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_24
	( 
	.cin(wire_counter_comb_bita_23cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_24cout[0:0]),
	.datad(counter_reg_bit[24]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_24sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_24.extended_lut = "off",
		counter_comb_bita_24.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_24.shared_arith = "off",
		counter_comb_bita_24.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_25
	( 
	.cin(wire_counter_comb_bita_24cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_25cout[0:0]),
	.datad(counter_reg_bit[25]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_25sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_25.extended_lut = "off",
		counter_comb_bita_25.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_25.shared_arith = "off",
		counter_comb_bita_25.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_26
	( 
	.cin(wire_counter_comb_bita_25cout[0:0]),
	.combout(),
	.cout(wire_counter_comb_bita_26cout[0:0]),
	.datad(counter_reg_bit[26]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_26sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_26.extended_lut = "off",
		counter_comb_bita_26.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_26.shared_arith = "off",
		counter_comb_bita_26.lpm_type = "cyclonev_lcell_comb";
	cyclonev_lcell_comb   counter_comb_bita_27
	( 
	.cin(wire_counter_comb_bita_26cout[0:0]),
	.combout(),
	.cout(),
	.datad(counter_reg_bit[27]),
	.dataf(updown_other_bits),
	.shareout(),
	.sumout(wire_counter_comb_bita_27sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		counter_comb_bita_27.extended_lut = "off",
		counter_comb_bita_27.lut_mask = 64'h0000FF000000FF00,
		counter_comb_bita_27.shared_arith = "off",
		counter_comb_bita_27.lpm_type = "cyclonev_lcell_comb";
	assign
		aclr_actual = 1'b0,
		clk_en = 1'b1,
		cnt_en = 1'b1,
		data = {28{1'b0}},
		external_cin = 1'b1,
		lsb_cin = 1'b0,
		q = safe_q,
		s_val = {28{1'b1}},
		safe_q = counter_reg_bit,
		sload = 1'b0,
		sset = 1'b0,
		updown_dir = 1'b1,
		updown_lsb = updown_dir,
		updown_other_bits = ((~ external_cin) | updown_dir);
endmodule //TwentyBitsCounter_cntr
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module TwentyBitsCounter (
	clock,
	sclr,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	  clock;
	input	  sclr;
	output	[27:0]  q;

	wire [27:0] sub_wire0;
	wire [27:0] q = sub_wire0[27:0];

	TwentyBitsCounter_cntr	TwentyBitsCounter_cntr_component (
				.clock (clock),
				.sclr (sclr),
				.q (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ACLR NUMERIC "0"
// Retrieval info: PRIVATE: ALOAD NUMERIC "0"
// Retrieval info: PRIVATE: ASET NUMERIC "0"
// Retrieval info: PRIVATE: ASET_ALL1 NUMERIC "1"
// Retrieval info: PRIVATE: CLK_EN NUMERIC "0"
// Retrieval info: PRIVATE: CNT_EN NUMERIC "0"
// Retrieval info: PRIVATE: CarryIn NUMERIC "0"
// Retrieval info: PRIVATE: CarryOut NUMERIC "0"
// Retrieval info: PRIVATE: Direction NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: PRIVATE: ModulusCounter NUMERIC "0"
// Retrieval info: PRIVATE: ModulusValue NUMERIC "0"
// Retrieval info: PRIVATE: SCLR NUMERIC "1"
// Retrieval info: PRIVATE: SLOAD NUMERIC "0"
// Retrieval info: PRIVATE: SSET NUMERIC "0"
// Retrieval info: PRIVATE: SSET_ALL1 NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: nBit NUMERIC "28"
// Retrieval info: PRIVATE: new_diagram STRING "1"
// Retrieval info: LIBRARY: lpm lpm.lpm_components.all
// Retrieval info: CONSTANT: LPM_DIRECTION STRING "UP"
// Retrieval info: CONSTANT: LPM_PORT_UPDOWN STRING "PORT_UNUSED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_COUNTER"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "28"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL "clock"
// Retrieval info: USED_PORT: q 0 0 28 0 OUTPUT NODEFVAL "q[27..0]"
// Retrieval info: USED_PORT: sclr 0 0 0 0 INPUT NODEFVAL "sclr"
// Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @sclr 0 0 0 0 sclr 0 0 0 0
// Retrieval info: CONNECT: q 0 0 28 0 @q 0 0 28 0
// Retrieval info: GEN_FILE: TYPE_NORMAL TwentyBitsCounter.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL TwentyBitsCounter.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL TwentyBitsCounter.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL TwentyBitsCounter.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL TwentyBitsCounter_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL TwentyBitsCounter_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL TwentyBitsCounter_syn.v TRUE
// Retrieval info: LIB_FILE: lpm
